version: "3.7"

services:
  postgres:
    image: postgres:12
    container_name: postgres
    ports:
      - "5432:5432"
    env_file:
      - .env.local
    volumes:
      - ./seeds:/var/lib/postgresql/data
